@startuml

title __MYSERVICE's Class Diagram__\n

  namespace com.myapp.organizeteam.MyService {
    interface com.myapp.organizeteam.MyService.APIService {
        {abstract} + sendNotification()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.Client {
        {static} - retrofit : Retrofit
        {static} + getClient()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.Data {
        - body : String
        - sented : String
        - title : String
        - user : String
        + Data()
        + getBody()
        + getSented()
        + getTitle()
        + getUser()
        + setBody()
        + setSented()
        + setTitle()
        + setUser()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.MeetingAlarmReceiver {
        ~ bundle : Bundle
        + onReceive()
        - sendNotification()
        - updateMeetingStatus()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.MyFirebaseMessagingService {
        - CHANNEL_ID : String
        + MyFirebaseMessagingService()
        + onMessageReceived()
        + onNewToken()
        - showNotification()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.Notification {
        + createClient()
        + createNotificationChannel()
        + sendNotification()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.Sender {
        + data : Data
        + to : String
        + Sender()
        + getData()
        + getTo()
        + setData()
        + setTo()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.TaskAlarmReceiver {
        ~ bundle : Bundle
        + onReceive()
        - updateTaskStatus()
    }
  }
  

  namespace com.myapp.organizeteam.MyService {
    class com.myapp.organizeteam.MyService.Token {
        - token : String
        - userID : String
        + Token()
        + getToken()
        + getUserID()
        + setToken()
        + setUserID()
    }
  }
  

  com.myapp.organizeteam.MyService.Data .up.|> java.io.Serializable
  com.myapp.organizeteam.MyService.Token .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
