@startuml

title __DIALOGS's Class Diagram__\n

  namespace com.myapp.organizeteam.Dialogs {
    class com.myapp.organizeteam.Dialogs.RequestJoinDialog {
        ~ dataExtraction : DataExtraction
        - CHANNEL_ID : String
        - hostToken : String
        - team : Team
        - tv_description : TextView
        - tv_name : TextView
        - userID : String
        - userName : String
        + onAttach()
        + onCreateDialog()
        - getAPIService()
        - sendNotification()
        - updateRequest()
    }
  }
  

  namespace com.myapp.organizeteam.Dialogs {
    interface com.myapp.organizeteam.Dialogs.RequestJoinDialog.DialogListener {
        {abstract} + applyRequest()
    }
  }
  

  namespace com.myapp.organizeteam.Dialogs {
    class com.myapp.organizeteam.Dialogs.TaskDialog {
        ~ activityTransition : ActivityTransition
        ~ dataExtraction : DataExtraction
        - btn_cancel : Button
        - btn_closeTask : Button
        - btn_submit : Button
        - btn_submittersList : Button
        - task : Mission
        - team : Team
        - tv_date : TextView
        - tv_description : TextView
        - tv_name : TextView
        - user : User
        + onAttach()
        + onCreateDialog()
        - backupTask()
        - setUI()
        - setUserStatus()
    }
  }
  

  com.myapp.organizeteam.Dialogs.RequestJoinDialog o-- com.myapp.organizeteam.Dialogs.RequestJoinDialog.DialogListener : listener
  com.myapp.organizeteam.Dialogs.RequestJoinDialog +-down- com.myapp.organizeteam.Dialogs.RequestJoinDialog.DialogListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
