@startuml

title __DATAMANAGEMENT's Class Diagram__\n

  namespace com.myapp.organizeteam.DataManagement {
    class com.myapp.organizeteam.DataManagement.Authorization {
        {static} + isManager : boolean
        ~ activityTransition : ActivityTransition
        ~ dataExtraction : DataExtraction
        + createNewUser()
        + createUser()
        + getUserID()
        + isEmailVerified()
        + login()
        + sendVerifyPhoneNumber()
        + sendVerifyPhoneNumber()
        + signInWithPhoneNumber()
        + singOut()
        + singOut()
        - sendTo()
    }
  }
  

  namespace com.myapp.organizeteam.DataManagement {
    class com.myapp.organizeteam.DataManagement.DataExtraction {
        + deleteData()
        + deleteToken()
        + deleteValue()
        + deleteValue()
        + getAllMeetingsByTeam()
        + getAllPostsByTeam()
        + getAllRolesByTeam()
        + getAllRolesByUser()
        + getAllTasksByTeam()
        + getAllUsersByTeam()
        + getChildsByKey()
        + getCurrentUserData()
        + getDeletedMeetingsByKeys()
        + getDeletedTasksByKeys()
        + getKeysByStatus()
        + getMeetingsByID()
        + getMeetingsByUser()
        + getPermissions()
        + getPostsByID()
        + getPostsByUser()
        + getRejects()
        + getResponse()
        + getResponsesOfSubmitter()
        + getSubmitter()
        + getSubmitters()
        + getTasksByID()
        + getTasksByUser()
        + getTeamDataByID()
        + getTeams()
        + getToken()
        + getUserDataByID()
        + getUsersByConfirmations()
        + getUsersByKeys()
        + getUsersByRoles()
        + hasChild()
        + hasChild()
        + hasChild()
        + isValueExist()
        + pushNewData()
        + setNewData()
        + setNewData()
        + setNewData()
        + setObject()
        + setObject()
        + setObject()
        + uploadPicture()
        - getDatabaseReference()
        - getListPermissions()
        - getRolesByID()
        - getRolesResult()
        - getTeamID()
        - getToken()
        - getValue()
        - removeDuplicateFromList()
    }
  }
  

  namespace com.myapp.organizeteam.DataManagement {
    interface com.myapp.organizeteam.DataManagement.DataListener {
        {abstract} + onDataDelete()
    }
  }
  

  namespace com.myapp.organizeteam.DataManagement {
    class com.myapp.organizeteam.DataManagement.DataPass {
        {static} + passData : Map<String, Object>
    }
  }
  

  namespace com.myapp.organizeteam.DataManagement {
    interface com.myapp.organizeteam.DataManagement.IRegister {
        {abstract} + onDone()
        {abstract} + onProcess()
    }
  }
  

  namespace com.myapp.organizeteam.DataManagement {
    interface com.myapp.organizeteam.DataManagement.ISavable {
        {abstract} + onDataRead()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
